title: "UPEI SMCSS"
tagline: "UPEI Society of Mathematical and Computational Science"
description: ""
github_username: upei-smcss
url: "https://github.com/upei-smcss/"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - README.md
  - join.md
  - discord.md

# set the size of the text to 'large' or 'small', default is small
font-size: small

remote_theme: tareqdandachi/jekyll-shell-theme
